# Generated by Django 4.1 on 2022-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloges',
            old_name='blog_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='bloges',
            name='creattion_date',
        ),
        migrations.AddField(
            model_name='bloges',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bloges',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloges',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
