# Generated by Django 4.1 on 2022-08-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_name_bloges_product_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloges',
        ),
    ]
