# Generated by Django 4.1 on 2022-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_chead0_alter_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='btime',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
