# Generated by Django 4.1 on 2022-08-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_btime_alter_blogpost_chead0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='btime',
        ),
    ]
