# Generated by Django 4.1 on 2022-08-21 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_btime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='btime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
