# Generated by Django 4.1 on 2022-08-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_btime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='btime',
        ),
    ]
