# Generated by Django 4.1 on 2022-08-21 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpost_btime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='btime',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 56, 42, 877487)),
        ),
    ]
