# Generated by Django 4.1 on 2022-08-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_btime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
