# Generated by Django 4.1 on 2022-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0013_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('head0', models.CharField(max_length=100)),
                ('chead0', models.CharField(default='', max_length=1000)),
                ('head1', models.CharField(default='', max_length=100, null=True)),
                ('chead1', models.CharField(default='', max_length=1000, null=True)),
                ('head2', models.CharField(default='', max_length=100, null=True)),
                ('chead2', models.CharField(default='', max_length=1000, null=True)),
                ('head3', models.CharField(default='', max_length=100, null=True)),
                ('chead3', models.CharField(default='', max_length=1000, null=True)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('btime', models.DateField()),
            ],
        ),
    ]
