# Generated by Django 4.1 on 2022-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='btime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='chead1',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='chead2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='chead3',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='head0',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='head1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='head2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='head3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.ImageField(default=',blank=True', upload_to='blog/images'),
        ),
    ]
