# Generated by Django 4.1 on 2022-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_postblog_btime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogstore',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cartjson', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PostBlog',
        ),
    ]
