# Generated by Django 4.1 on 2022-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogstore_delete_postblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('pubdate', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('available', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogstore',
        ),
    ]
