# Generated by Django 4.1 on 2022-08-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpost_delete_blogstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pubdate',
        ),
    ]
