# Generated by Django 4.1 on 2022-08-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_blogpost_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='available',
        ),
    ]
