# Generated by Django 4.1 on 2022-08-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blogpost_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subcategory',
        ),
    ]
