# Generated by Django 4.1 on 2022-08-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_blogpost_category_remove_blogpost_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
