# Generated by Django 4.1 on 2022-08-21 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpost_head0'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 23, 33, 55, 623032)),
        ),
    ]
