# Generated by Django 4.1 on 2022-08-21 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_blogpost_name_blogpost_chead0_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 56, 19, 423548)),
        ),
    ]
