# Generated by Django 4.1 on 2022-08-25 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_blogpost_about_alter_blogpost_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 23, 1, 59, 865146)),
        ),
    ]
