# Generated by Django 4.1 on 2022-08-28 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_blogpost_about_remove_blogpost_bdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 17, 10, 9, 614467)),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='titel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
