# Generated by Django 4.1 on 2022-08-28 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_topblog_alter_blogpost_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 17, 19, 19, 99335)),
        ),
    ]
