# Generated by Django 4.1 on 2022-08-29 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_topblog_date_topblog_title_alter_blogpost_bdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.AlterField(
            model_name='topblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 13, 44, 24, 760097)),
        ),
    ]
