# Generated by Django 4.1 on 2022-08-29 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_delete_blogpost_alter_topblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 13, 46, 31, 402168)),
        ),
    ]
