# Generated by Django 4.1 on 2022-08-29 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_topblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topblog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
