# Generated by Django 4.1 on 2022-08-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_topblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topblog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
