# Generated by Django 4.1 on 2022-08-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_topblog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topblog',
            name='date',
        ),
    ]
