# Generated by Django 4.1 on 2022-08-29 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_topblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topblog',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 29)),
        ),
    ]
