# Generated by Django 4.1 on 2022-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_topblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topblog',
            name='auther',
            field=models.CharField(default='Tenali', max_length=50),
        ),
    ]
