# Generated by Django 4.1 on 2022-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_topblog_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='topblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
