# Generated by Django 4.1 on 2022-08-30 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_topblog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topblog',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topblog',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 30)),
        ),
    ]
