# Generated by Django 4.1 on 2022-08-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
