# Generated by Django 4.1 on 2022-08-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
