# Generated by Django 4.1 on 2022-08-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
