# Generated by Django 4.1 on 2022-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_desc_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('birthday', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(default='', upload_to='shop/profiles')),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
