# Generated by Django 4.1 on 2022-08-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
