# Generated by Django 4.1 on 2022-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpadate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=500)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
