# Generated by Django 4.1 on 2022-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderupadate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='cartjson',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
