# Generated by Django 4.1 on 2022-08-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_orderaddress_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpadate',
            new_name='orderupdate',
        ),
    ]
