# Generated by Django 4.1 on 2022-08-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_orderupadate_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='addr_id',
        ),
    ]
