# Generated by Django 4.1 on 2022-08-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_id_orders_addr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='id',
            new_name='up_id',
        ),
    ]
