# Generated by Django 4.1 on 2022-08-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_id_orderupdate_up_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='orderupdate',
        ),
    ]
