# Generated by Django 4.1 on 2022-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_delete_orders_delete_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cartjson', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('up_id', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=500)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
