# Generated by Django 4.1 on 2022-08-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_image_product_cimage_product_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cimage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
    ]
